site_name: Turftopic
site_description: 'An all-in-one library for topic modeling with sentence embeddings.'
repo_url: https://github.com/x-tabdeveloping/turftopic
nav:
  - Home: index.md
  - Models:
    - KeyNMF: KeyNMF.md
    - S³: s3.md
    - GMM: GMM.md
    - Clustering Models: clustering.md
    - Autoencoding Models: ctm.md
  - Encoders: encoders.md
theme:
  name: material
  logo: images/logo.svg
  palette:
    primary: '#01034A'
  features:
      - toc.integrate
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.indexes
      - toc.follow
      - content.code.copy

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          annotations_path: brief
          show_root_heading: false
          show_root_toc_entry: false
          show_symbol_type_heading: true
    custom_templates: templates    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
